export type TarotCard = {
  id: number
  /** DB lookup 키 — seed.ts의 slug와 1:1 매칭 */
  slug: string
  name: string
  numeral: string
  type: "major" | "minor"
  suit?: "wands" | "cups" | "swords" | "pentacles"
  keywords: string[]
  upright: string
  /** DB image_url 또는 mock CDN — 없으면 getTarotCardImageUrl(slug)로 해석 */
  imageUrl?: string | null
}

export const TAROT_DECK: TarotCard[] = [
  // ── Major Arcana (22) ─────────────────────────────────────────────────
  {
    id: 0,
    slug: "the-fool",
    name: "The Fool",
    numeral: "0",
    type: "major",
    keywords: ["beginnings", "innocence", "adventure"],
    upright: "New beginnings, spontaneity, a free spirit",
  },
  {
    id: 1,
    slug: "the-magician",
    name: "The Magician",
    numeral: "I",
    type: "major",
    keywords: ["manifestation", "power", "skill"],
    upright: "Manifestation, resourcefulness, inspired action",
  },
  {
    id: 2,
    slug: "the-high-priestess",
    name: "The High Priestess",
    numeral: "II",
    type: "major",
    keywords: ["intuition", "mystery", "inner voice"],
    upright: "Intuition, sacred knowledge, divine feminine",
  },
  {
    id: 3,
    slug: "the-empress",
    name: "The Empress",
    numeral: "III",
    type: "major",
    keywords: ["fertility", "abundance", "nature"],
    upright: "Femininity, beauty, nature, abundance",
  },
  {
    id: 4,
    slug: "the-emperor",
    name: "The Emperor",
    numeral: "IV",
    type: "major",
    keywords: ["authority", "structure", "stability"],
    upright: "Authority, establishment, structure, a father figure",
  },
  {
    id: 5,
    slug: "the-hierophant",
    name: "The Hierophant",
    numeral: "V",
    type: "major",
    keywords: ["tradition", "conformity", "morality"],
    upright: "Spiritual wisdom, religious beliefs, conformity",
  },
  {
    id: 6,
    slug: "the-lovers",
    name: "The Lovers",
    numeral: "VI",
    type: "major",
    keywords: ["love", "harmony", "relationships"],
    upright: "Love, harmony, relationships, values alignment",
  },
  {
    id: 7,
    slug: "the-chariot",
    name: "The Chariot",
    numeral: "VII",
    type: "major",
    keywords: ["control", "willpower", "success"],
    upright: "Control, willpower, success, determination",
  },
  {
    id: 8,
    slug: "strength",
    name: "Strength",
    numeral: "VIII",
    type: "major",
    keywords: ["courage", "patience", "inner strength"],
    upright: "Strength, courage, patience, control",
  },
  {
    id: 9,
    slug: "the-hermit",
    name: "The Hermit",
    numeral: "IX",
    type: "major",
    keywords: ["soul-searching", "solitude", "introspection"],
    upright: "Soul-searching, introspection, being alone",
  },
  {
    id: 10,
    slug: "wheel-of-fortune",
    name: "Wheel of Fortune",
    numeral: "X",
    type: "major",
    keywords: ["good luck", "karma", "life cycles"],
    upright: "Good luck, karma, life cycles, destiny",
  },
  {
    id: 11,
    slug: "justice",
    name: "Justice",
    numeral: "XI",
    type: "major",
    keywords: ["fairness", "truth", "cause and effect"],
    upright: "Justice, fairness, truth, cause and effect",
  },
  {
    id: 12,
    slug: "the-hanged-man",
    name: "The Hanged Man",
    numeral: "XII",
    type: "major",
    keywords: ["pause", "surrender", "new perspectives"],
    upright: "Pause, surrender, letting go, new perspectives",
  },
  {
    id: 13,
    slug: "death",
    name: "Death",
    numeral: "XIII",
    type: "major",
    keywords: ["endings", "change", "transformation"],
    upright: "Endings, change, transformation, transition",
  },
  {
    id: 14,
    slug: "temperance",
    name: "Temperance",
    numeral: "XIV",
    type: "major",
    keywords: ["balance", "moderation", "patience"],
    upright: "Balance, moderation, patience, purpose",
  },
  {
    id: 15,
    slug: "the-devil",
    name: "The Devil",
    numeral: "XV",
    type: "major",
    keywords: ["shadow self", "attachment", "addiction"],
    upright: "Shadow self, attachment, addiction, restriction",
  },
  {
    id: 16,
    slug: "the-tower",
    name: "The Tower",
    numeral: "XVI",
    type: "major",
    keywords: ["sudden change", "upheaval", "chaos"],
    upright: "Sudden change, upheaval, chaos, revelation",
  },
  {
    id: 17,
    slug: "the-star",
    name: "The Star",
    numeral: "XVII",
    type: "major",
    keywords: ["hope", "faith", "rejuvenation"],
    upright: "Hope, faith, purpose, renewal, spirituality",
  },
  {
    id: 18,
    slug: "the-moon",
    name: "The Moon",
    numeral: "XVIII",
    type: "major",
    keywords: ["illusion", "fear", "the unconscious"],
    upright: "Illusion, fear, the unconscious, confusion",
  },
  {
    id: 19,
    slug: "the-sun",
    name: "The Sun",
    numeral: "XIX",
    type: "major",
    keywords: ["positivity", "fun", "warmth"],
    upright: "Positivity, fun, warmth, success, vitality",
  },
  {
    id: 20,
    slug: "judgement",
    name: "Judgement",
    numeral: "XX",
    type: "major",
    keywords: ["reflection", "reckoning", "awakening"],
    upright: "Judgement, rebirth, inner calling, absolution",
  },
  {
    id: 21,
    slug: "the-world",
    name: "The World",
    numeral: "XXI",
    type: "major",
    keywords: ["completion", "integration", "accomplishment"],
    upright: "Completion, integration, accomplishment, travel",
  },

  // ── Minor Arcana — Wands (14) ──────────────────────────────────────────
  {
    id: 100,
    slug: "ace-of-wands",
    name: "Ace of Wands",
    numeral: "A",
    type: "minor",
    suit: "wands",
    keywords: ["inspiration", "new initiative", "energy"],
    upright: "Inspiration, new opportunities, growth",
  },
  {
    id: 101,
    slug: "two-of-wands",
    name: "Two of Wands",
    numeral: "2",
    type: "minor",
    suit: "wands",
    keywords: ["planning", "future", "progress"],
    upright: "Future planning, progress, discovery",
  },
  {
    id: 102,
    slug: "three-of-wands",
    name: "Three of Wands",
    numeral: "3",
    type: "minor",
    suit: "wands",
    keywords: ["expansion", "foresight", "overseas"],
    upright: "Expansion, foresight, overseas opportunities",
  },
  {
    id: 103,
    slug: "four-of-wands",
    name: "Four of Wands",
    numeral: "4",
    type: "minor",
    suit: "wands",
    keywords: ["celebration", "harmony", "homecoming"],
    upright: "Celebration, joy, harmony, relaxation",
  },
  {
    id: 104,
    slug: "five-of-wands",
    name: "Five of Wands",
    numeral: "5",
    type: "minor",
    suit: "wands",
    keywords: ["conflict", "disagreements", "competition"],
    upright: "Conflict, disagreements, competition, tension",
  },
  {
    id: 105,
    slug: "six-of-wands",
    name: "Six of Wands",
    numeral: "6",
    type: "minor",
    suit: "wands",
    keywords: ["success", "public recognition", "progress"],
    upright: "Success, public recognition, progress, self-confidence",
  },
  {
    id: 106,
    slug: "seven-of-wands",
    name: "Seven of Wands",
    numeral: "7",
    type: "minor",
    suit: "wands",
    keywords: ["challenge", "perseverance", "defense"],
    upright: "Challenge, competition, perseverance, standing tall",
  },
  {
    id: 107,
    slug: "eight-of-wands",
    name: "Eight of Wands",
    numeral: "8",
    type: "minor",
    suit: "wands",
    keywords: ["speed", "action", "air travel"],
    upright: "Speed, action, air travel, movement, swift change",
  },
  {
    id: 108,
    slug: "nine-of-wands",
    name: "Nine of Wands",
    numeral: "9",
    type: "minor",
    suit: "wands",
    keywords: ["resilience", "grit", "persistence"],
    upright: "Resilience, courage, persistence, test of faith",
  },
  {
    id: 109,
    slug: "ten-of-wands",
    name: "Ten of Wands",
    numeral: "10",
    type: "minor",
    suit: "wands",
    keywords: ["burden", "extra responsibility", "hard work"],
    upright: "Burden, extra responsibility, hard work, completion",
  },
  {
    id: 110,
    slug: "page-of-wands",
    name: "Page of Wands",
    numeral: "P",
    type: "minor",
    suit: "wands",
    keywords: ["exploration", "excitement", "freedom"],
    upright: "Exploration, excitement, freedom, adventure",
  },
  {
    id: 111,
    slug: "knight-of-wands",
    name: "Knight of Wands",
    numeral: "Kn",
    type: "minor",
    suit: "wands",
    keywords: ["energy", "passion", "adventure"],
    upright: "Energy, passion, inspired action, adventure",
  },
  {
    id: 112,
    slug: "queen-of-wands",
    name: "Queen of Wands",
    numeral: "Q",
    type: "minor",
    suit: "wands",
    keywords: ["courage", "confidence", "enthusiasm"],
    upright: "Courage, confidence, independence, social butterfly",
  },
  {
    id: 113,
    slug: "king-of-wands",
    name: "King of Wands",
    numeral: "K",
    type: "minor",
    suit: "wands",
    keywords: ["natural-born leader", "vision", "entrepreneur"],
    upright: "Natural-born leader, vision, entrepreneur, honour",
  },

  // ── Minor Arcana — Cups (14) ───────────────────────────────────────────
  {
    id: 200,
    slug: "ace-of-cups",
    name: "Ace of Cups",
    numeral: "A",
    type: "minor",
    suit: "cups",
    keywords: ["love", "new feelings", "intuition"],
    upright: "Love, new feelings, emotional awakening",
  },
  {
    id: 201,
    slug: "two-of-cups",
    name: "Two of Cups",
    numeral: "2",
    type: "minor",
    suit: "cups",
    keywords: ["unity", "partnership", "connection"],
    upright: "Unity, partnership, mutual attraction",
  },
  {
    id: 202,
    slug: "three-of-cups",
    name: "Three of Cups",
    numeral: "3",
    type: "minor",
    suit: "cups",
    keywords: ["celebration", "friendship", "creativity"],
    upright: "Celebration, friendship, creativity, community",
  },
  {
    id: 203,
    slug: "four-of-cups",
    name: "Four of Cups",
    numeral: "4",
    type: "minor",
    suit: "cups",
    keywords: ["meditation", "contemplation", "apathy"],
    upright: "Meditation, contemplation, apathy, re-evaluation",
  },
  {
    id: 204,
    slug: "five-of-cups",
    name: "Five of Cups",
    numeral: "5",
    type: "minor",
    suit: "cups",
    keywords: ["regret", "failure", "disappointment"],
    upright: "Regret, failure, disappointment, pessimism",
  },
  {
    id: 205,
    slug: "six-of-cups",
    name: "Six of Cups",
    numeral: "6",
    type: "minor",
    suit: "cups",
    keywords: ["nostalgia", "childhood", "innocence"],
    upright: "Revisiting the past, childhood memories, innocence",
  },
  {
    id: 206,
    slug: "seven-of-cups",
    name: "Seven of Cups",
    numeral: "7",
    type: "minor",
    suit: "cups",
    keywords: ["fantasy", "illusion", "wishful thinking"],
    upright: "Opportunities, choices, wishful thinking",
  },
  {
    id: 207,
    slug: "eight-of-cups",
    name: "Eight of Cups",
    numeral: "8",
    type: "minor",
    suit: "cups",
    keywords: ["disappointment", "abandonment", "withdrawal"],
    upright: "Disappointment, abandonment, withdrawal",
  },
  {
    id: 208,
    slug: "nine-of-cups",
    name: "Nine of Cups",
    numeral: "9",
    type: "minor",
    suit: "cups",
    keywords: ["contentment", "satisfaction", "gratitude"],
    upright: "Contentment, satisfaction, gratitude, wish fulfilled",
  },
  {
    id: 209,
    slug: "ten-of-cups",
    name: "Ten of Cups",
    numeral: "10",
    type: "minor",
    suit: "cups",
    keywords: ["happiness", "fulfillment", "harmony"],
    upright: "Divine love, blissful relationships, harmony",
  },
  {
    id: 210,
    slug: "page-of-cups",
    name: "Page of Cups",
    numeral: "P",
    type: "minor",
    suit: "cups",
    keywords: ["creative opportunities", "curiosity", "possibility"],
    upright: "Creative opportunities, curiosity, possibility",
  },
  {
    id: 211,
    slug: "knight-of-cups",
    name: "Knight of Cups",
    numeral: "Kn",
    type: "minor",
    suit: "cups",
    keywords: ["creativity", "romance", "charm"],
    upright: "Creativity, romance, charm, imagination",
  },
  {
    id: 212,
    slug: "queen-of-cups",
    name: "Queen of Cups",
    numeral: "Q",
    type: "minor",
    suit: "cups",
    keywords: ["compassionate", "caring", "emotionally stable"],
    upright: "Compassionate, caring, emotionally stable, intuitive",
  },
  {
    id: 213,
    slug: "king-of-cups",
    name: "King of Cups",
    numeral: "K",
    type: "minor",
    suit: "cups",
    keywords: ["emotionally balanced", "compassionate", "diplomatic"],
    upright: "Emotionally balanced, compassionate, diplomatic",
  },

  // ── Minor Arcana — Swords (14) ─────────────────────────────────────────
  {
    id: 300,
    slug: "ace-of-swords",
    name: "Ace of Swords",
    numeral: "A",
    type: "minor",
    suit: "swords",
    keywords: ["clarity", "breakthrough", "new idea"],
    upright: "Breakthrough, clarity, sharp mind",
  },
  {
    id: 301,
    slug: "two-of-swords",
    name: "Two of Swords",
    numeral: "2",
    type: "minor",
    suit: "swords",
    keywords: ["difficult decisions", "indecision", "stalemate"],
    upright: "Difficult choices, indecision, information overload",
  },
  {
    id: 302,
    slug: "three-of-swords",
    name: "Three of Swords",
    numeral: "3",
    type: "minor",
    suit: "swords",
    keywords: ["heartbreak", "suffering", "grief"],
    upright: "Heartbreak, suffering, grief, rejection",
  },
  {
    id: 303,
    slug: "four-of-swords",
    name: "Four of Swords",
    numeral: "4",
    type: "minor",
    suit: "swords",
    keywords: ["rest", "recovery", "contemplation"],
    upright: "Rest, recovery, contemplation, peace",
  },
  {
    id: 304,
    slug: "five-of-swords",
    name: "Five of Swords",
    numeral: "5",
    type: "minor",
    suit: "swords",
    keywords: ["conflict", "defeat", "win at all costs"],
    upright: "Conflict, disagreements, competition, defeat",
  },
  {
    id: 305,
    slug: "six-of-swords",
    name: "Six of Swords",
    numeral: "6",
    type: "minor",
    suit: "swords",
    keywords: ["transition", "change", "rite of passage"],
    upright: "Transition, change, rite of passage, moving on",
  },
  {
    id: 306,
    slug: "seven-of-swords",
    name: "Seven of Swords",
    numeral: "7",
    type: "minor",
    suit: "swords",
    keywords: ["betrayal", "deception", "getting away with something"],
    upright: "Betrayal, deception, getting away with something",
  },
  {
    id: 307,
    slug: "eight-of-swords",
    name: "Eight of Swords",
    numeral: "8",
    type: "minor",
    suit: "swords",
    keywords: ["imprisonment", "entrapment", "self-victimization"],
    upright: "Restriction, imprisonment, powerlessness",
  },
  {
    id: 308,
    slug: "nine-of-swords",
    name: "Nine of Swords",
    numeral: "9",
    type: "minor",
    suit: "swords",
    keywords: ["anxiety", "worry", "fear"],
    upright: "Anxiety, worry, fear, depression, nightmares",
  },
  {
    id: 309,
    slug: "ten-of-swords",
    name: "Ten of Swords",
    numeral: "10",
    type: "minor",
    suit: "swords",
    keywords: ["painful endings", "deep wounds", "betrayal"],
    upright: "Painful endings, deep wounds, betrayal, rock bottom",
  },
  {
    id: 310,
    slug: "page-of-swords",
    name: "Page of Swords",
    numeral: "P",
    type: "minor",
    suit: "swords",
    keywords: ["new ideas", "curiosity", "thirst for knowledge"],
    upright: "New ideas, curiosity, thirst for knowledge",
  },
  {
    id: 311,
    slug: "knight-of-swords",
    name: "Knight of Swords",
    numeral: "Kn",
    type: "minor",
    suit: "swords",
    keywords: ["ambitious", "action-oriented", "driven"],
    upright: "Ambitious, action-oriented, driven to succeed",
  },
  {
    id: 312,
    slug: "queen-of-swords",
    name: "Queen of Swords",
    numeral: "Q",
    type: "minor",
    suit: "swords",
    keywords: ["independent", "unbiased judgement", "clear boundaries"],
    upright: "Independent, unbiased judgement, clear boundaries",
  },
  {
    id: 313,
    slug: "king-of-swords",
    name: "King of Swords",
    numeral: "K",
    type: "minor",
    suit: "swords",
    keywords: ["mental clarity", "intellectual power", "authority"],
    upright: "Mental clarity, intellectual power, truth, authority",
  },

  // ── Minor Arcana — Pentacles (14) ──────────────────────────────────────
  {
    id: 400,
    slug: "ace-of-pentacles",
    name: "Ace of Pentacles",
    numeral: "A",
    type: "minor",
    suit: "pentacles",
    keywords: ["opportunity", "prosperity", "new venture"],
    upright: "A new financial opportunity, manifestation, abundance",
  },
  {
    id: 401,
    slug: "two-of-pentacles",
    name: "Two of Pentacles",
    numeral: "2",
    type: "minor",
    suit: "pentacles",
    keywords: ["multiple priorities", "time management", "adaptation"],
    upright: "Multiple priorities, time management, adaptability",
  },
  {
    id: 402,
    slug: "three-of-pentacles",
    name: "Three of Pentacles",
    numeral: "3",
    type: "minor",
    suit: "pentacles",
    keywords: ["teamwork", "collaboration", "building"],
    upright: "Teamwork, collaboration, learning, implementation",
  },
  {
    id: 403,
    slug: "four-of-pentacles",
    name: "Four of Pentacles",
    numeral: "4",
    type: "minor",
    suit: "pentacles",
    keywords: ["saving", "security", "conservatism"],
    upright: "Saving money, security, conservatism, scarcity",
  },
  {
    id: 404,
    slug: "five-of-pentacles",
    name: "Five of Pentacles",
    numeral: "5",
    type: "minor",
    suit: "pentacles",
    keywords: ["financial loss", "poverty", "lack"],
    upright: "Financial loss, poverty, lack, insecurity",
  },
  {
    id: 405,
    slug: "six-of-pentacles",
    name: "Six of Pentacles",
    numeral: "6",
    type: "minor",
    suit: "pentacles",
    keywords: ["generosity", "charity", "giving"],
    upright: "Generosity, charity, giving, prosperity sharing",
  },
  {
    id: 406,
    slug: "seven-of-pentacles",
    name: "Seven of Pentacles",
    numeral: "7",
    type: "minor",
    suit: "pentacles",
    keywords: ["long-term view", "sustainable results", "perseverance"],
    upright: "Long-term view, sustainable results, perseverance",
  },
  {
    id: 407,
    slug: "eight-of-pentacles",
    name: "Eight of Pentacles",
    numeral: "8",
    type: "minor",
    suit: "pentacles",
    keywords: ["apprenticeship", "skill development", "dedication"],
    upright: "Apprenticeship, repetitive tasks, mastery, skill development",
  },
  {
    id: 408,
    slug: "nine-of-pentacles",
    name: "Nine of Pentacles",
    numeral: "9",
    type: "minor",
    suit: "pentacles",
    keywords: ["abundance", "luxury", "self-sufficiency"],
    upright: "Abundance, luxury, self-sufficiency, financial independence",
  },
  {
    id: 409,
    slug: "ten-of-pentacles",
    name: "Ten of Pentacles",
    numeral: "10",
    type: "minor",
    suit: "pentacles",
    keywords: ["wealth", "inheritance", "family"],
    upright: "Wealth, financial security, family, long-term success",
  },
  {
    id: 410,
    slug: "page-of-pentacles",
    name: "Page of Pentacles",
    numeral: "P",
    type: "minor",
    suit: "pentacles",
    keywords: ["manifestation", "financial opportunity", "skill development"],
    upright: "Manifestation, financial opportunity, skill development",
  },
  {
    id: 411,
    slug: "knight-of-pentacles",
    name: "Knight of Pentacles",
    numeral: "Kn",
    type: "minor",
    suit: "pentacles",
    keywords: ["hard work", "productivity", "routine"],
    upright: "Hard work, productivity, routine, conservatism",
  },
  {
    id: 412,
    slug: "queen-of-pentacles",
    name: "Queen of Pentacles",
    numeral: "Q",
    type: "minor",
    suit: "pentacles",
    keywords: ["nurturing", "practical", "homebody"],
    upright: "Nurturing, practical, providing financially, working parent",
  },
  {
    id: 413,
    slug: "king-of-pentacles",
    name: "King of Pentacles",
    numeral: "K",
    type: "minor",
    suit: "pentacles",
    keywords: ["abundance", "prosperity", "security"],
    upright: "Abundance, prosperity, security, ambition",
  },
]
